Exam/quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	
	path('tquiz/'  ,include('tquiz.urls')),

    path('admin/', admin.site.urls),
]

Exam/tquiz/urls.py
from django.urls import path

from . import views


app_name = 'tquiz'

urlpatterns = [

	path("", views.Index.as_view(), name ='index'),
	
	path("results/", views.Results.as_view(), name ='results'),

	path("startwork/<quiz_name>", views.StartWork.as_view(), name ='startwork'),

	path("search/<query>", views.SearchResult.as_view(), name ='search'),

	path("quiz/", views.Quiz.as_view(), name ='quiz'),

]

Exam/tquiz/models.py
from django.db import models
import time

# Create your models here.

class Examiner(models.Model):
	name = models.CharField(max_length=100, default="Anonymous")
	info = models.TextField(default="No information available")

class QuizCatalog(models.Model):
	examiner = models.ForeignKey(Examiner, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	programme = models.CharField(max_length=255, default="general")
	course = models.CharField(max_length=255, default="general paper")
	level = models.IntegerField(default=100)
	image = models.CharField(max_length=50)
	allocated_time = models.IntegerField(default=10)
	rating = models.CharField(max_length=50, default="normal")
	date = models.CharField(max_length=25, default=time.asctime())


class Question(models.Model):
	quiz_catalog = models.ForeignKey(QuizCatalog, on_delete=models.CASCADE)
	question = models.TextField()
	answer = models.TextField()


class Choice(models.Model):
	answer = models.ForeignKey(Question,on_delete = models.CASCADE)
	choice = models.TextField()

class Tutorials(models.Model):
	form = models.CharField(max_length=15)


	

Exam/tquiz/views.py
from django.shortcuts import render
from django.views import View
from .models import Question, Choice, QuizCatalog
from .utility_functions import *

# Create your views here.

class Index(View):
	
	quizList = QuizCatalog.objects.all()[:10]
	
	
	def get (self, request):

		self.template = "tquiz/index.html"
		
		self.context = {"quizList" : self.quizList}
		
		return render(request, self.template, self.context)


				
class Results(View):
	
	questions = Question.objects.all()
	
	def post(self, request):
		
		sub_ans = request.POST
		
		results = mark(sub_ans, self.questions)
		
		self.template = 'tquiz/results.html'
		
		self.context = {'results' : results}
		
		return render(request, self.template, self.context)
		
	def get(self, request):
		
		self.template = "tquiz/no-results.html"
			
		self.context = {}
			
		return render(request, self.template, self.context)
			


class StartWork(View):

	def get(self, request, quiz_name):
		quiz = QuizCatalog.objects.get(name=quiz_name)
		questions = quiz.question_set.all()
		qc_dict = {}
		for question in questions:
			choice = question.choice_set.all()
			qc_dict[question.question] = choice

		questionList = shuffler(qc_dict)


		self.template = 'tquiz/start-work.html'
		self.context = {'questionList':questionList}

		return render(request, self.template, self.context)

class SearchResult(View):
	def get(self, request, query):
		quiz_results = quiz_results(query)
		quiz_numbers = len(quiz_results)
		tutorials_results = tutorials_results(query)
		tutorials_number = len(tutorials_results)
		qns_results = qns_results(query)
		quiz_number = len(qns_results)
		query = query
		self.template = 'tquiz/serach-result.html'
		self.context = {'quiz_results': quiz_results, 
						'quiz_number': quiz_number,
						'tutorials_results': tutorials_results, 
						'tutorials_number': tutorials_number,
						'qns_results': qns_results, 
						'qns_number': qns_number,
						 'query': query}
		return render(request, self.template, self.context)


class Quiz(View):
	def get(self, request):
		quizList = QuizCatalog.objects.all()[:10]
		self.template = 'tquiz/quiz.html'
		self.context = {"quizList": quizList}

		return render(request, self.template, self.context)

Exam/tquiz/templates/tquiz/base.html
<html>

<head>

<meta charset="utf-8">
<title>Time quiz</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

   {% load static %}
    <link rel="stylesheet" href="{% static 'tquiz/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'tquiz/vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'tquiz/vendor/w3/w3.css' %}">
    <link rel="stylesheet" href="{% static 'tquiz/vendor/font-awesome/css/font-awesome.css' %}">
</head>

<body>
<!-- top card -->
<div class="w3-card-2 w3-top w3-blue">
<!-- navbar row -->
<div class="w3-row">
<!-- navbar -->
<div class="w3-bar w3-padding">
<div class="w3-bar-item w3-left w3-xlarge">
<i class="fa fa-bars" id="bars"></i></div>

<div class="w3-bar-item w3-large"><a href="{% url 'tquiz:index' %}">Tquiz</a></div>

<div class="w3-bar-item w3-right w3-xlarge">
<i class="fa fa-search" id="search-icon" ></i>
</div>

<div class="w3-bar-item w3-right w3-xlarge">
<i class="fa fa-user" id="account"></i></div>
</div>
</div>

<!-- end of top card -->
</div>


<div class="overlay-menu" id="menu">
<!-- overlay menu content -->
<div class="overlay-menu-content">
</div>
</div>

<!-- overlay search -->
<div class="w3-row overlay-search" id="search">

<div class="w3-col">
<div class="overlay-search-content" id="search-input">
	<form method="get" action="">
		{% csrf_token %}
		<input type="text" name="query" placeholder="Search quizes, turorials and questions" class="w3-input w3-margin separator w3-large w3-padding"><br>
		<input type="submit" value="Search" class="w3-center w3-input w3-padding w3-large w3-blue w3-margin w3-round-large">
	</form>
</div>
</div>

<div class="w3-col" id="close-search" style="height: 100%; "></div>

</div>
{% block content %}


{% endblock %}


{% load static %}

<!-- footer -->

<footer style="position: relative; top: 100px">
<div class="w3-row">

<div class="w3-col s6">

<p ><a href="#" >Terms and Conditons<a></p>

</div>

<div class="w3-col l4 s6">

<p>&copy; Tquiz 2020</p>

</div>

</div>


</footer>

</body>

{% load static %}
<script src=" {% static 'tquiz/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>

<script src=" {% static 'tquiz/vendor/font-awesome/css/font-awesome.css' %}"></script>

<script src=" {% static 'tquiz/vendor/jquery/jquery.js' %}"></script>

<script src=" {% static 'tquiz/js/custom.js' %}"></script>

</html>

Exam/tquiz/templates/tquiz/index.html
{% extends './base.html' %}

{% block content %}

<div style="position: relative; top: 100px;">

	<div class="w3-row w3-bar w3-blue">
	<!-- optionNav -->
		<div class="w3-col active s4 w3-center tabNav quiz"><h5>Quiz</h5></div>

		<div class="w3-col s4 w3-center tabNav tutorials"><h5>Tutorials</h5></div>

		<div class="w3-col s4 w3-center tabNav q-n-a"><h5>Q & A</h5></div>
	</div>

	<!-- div for quiz -->
	<div class="tabContent" id="quiz">
		<div class="w3-row w3-margin">
			{% for quiz in quizList %}
			<div class="w3-col l3 m5 s11 w3-card-4 w3-round">
				<a href="{% url 'tquiz:startwork' quiz.name %}">
					<ul class="w3-col s8">
						<li>Name: {{quiz.name}} </li>
						<li>Course: {{quiz.course}} </li>
						<li> Subject: {{quiz.subject}} </li>
						<li> Time : {{quiz.time}}</li>
					</ul>
				
					<div class="w3-col s4">
						{% load static %}
						<img src="{% static 'tquiz/img/myself.jpg' %}" class="w3-image w3-round">
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>


	<!-- div for Tutorials -->
	<div class="tabContent w3-hide" id="tutorials">
		<div class="w3-row l3 m5 s11 w3-card-2 w3-margin">
			<div class="w3-col s6 w3-margin">
				<h5>Course: RGN </h5>
				<h5> Subject: Anatomy I </h5>
				<h5> Level: 100 </h5>
			</div>
			<div class="w3-col s4">
				<img src="" class="w3-image">
			</div>
		</div>
	</div>

	<!-- div for Q&A -->
	<div class="tabContent w3-hide" id="q-n-a">
		<div class="w3-row l3 m5 s11 w3-card-2 w3-margin">
			<div class="w3-col s6 w3-margin">
				<h5>Questions</h5>
				<h5> Subject: Anatomy I </h5>
				<h5> Level: 100 </h5>
			</div>
			<div class="w3-col s4">
				<img src="" class="w3-image">
			</div>
		</div>
	</div>
</div>

{% endblock %}

Exam/tquiz/templates/tquiz/mati.html
<!DOCTYPE html>
<html>
<head>
<title>moazl</title>
<style>
.speech{
	position: relative;
	top: 10px;
	width: 100px;
	height: 50px;
	border : 5px solid black;
	background-color: white;
	border-radius: 10%;
}

.speech:before{
	content: "";
	width: 0px;
	height: 0px;
	position: absolute;
	top: 55px;
	left: 45px;
	border: 15px solid;
	background-color: white;
	border-color: black transparent transparent black;
}
.speech:after{
	content: "";
	width: 0px;
	height: 0px;
	position: absolute;
	top: 50px;
	left: 50px;
	border: 10px solid;
	border-color: white transparent transparent white;
}
</style>
</head>
<body>
<p class='speech'>How are you doing?</p>
</body>
</html>

Exam/tquiz/templates/tquiz/no-results.html
{% extends './base.html' %}


{% block content %}

<div style="position: relative; top: 100px;">
	<div class="w3-card-4 w3-margin">
		<div class="w3-padding">
			<p>Hellooo, buddy there is no result available for you. <br>
			This is probably because you have not taken any quiz yet. </p>
			<p> Please click <a href="/tquiz" style="color: blue;" >here</a> to take an exciting and challenging quiz</p>
		</div>
	</div>
</div>



{% endblock %}

Exam/tquiz/templates/tquiz/quiz.html
{% extends './base.html' %}
{% block content %}
<div style="position: relative; top: 70px;">
	<div class="row w3-blue w3-bar">
		<div class="actionNav w3-center w3-col s4 m4 w3-border-right w3-button" id="filter">Filter<span class="fa fa-filter w3-margin-left"></span></div>
		<div class="actionNav w3-center w3-col s4 m4 w3-border-right w3-button" id="random">Random<span class="fa fa-random w3-margin-left"></span></div>
		<div class="actionNav w3-center w3-col s4 m4 w3-button" id="sort">Sort<span class="fa fa-sort w3-margin-left"></span></div>
	</div>

	<!-- filters -->
	<div class="overlay-action w3-row" id="f-content">
		<div class="overlay-action-content">
			<p class="w3-large">Please select the kind of filter you want to apply</p>
			<form>
				<div class="w3-col s5 w3-margin">
					<ul>
						<li>Level</li>
						<input type="checkbox" name="100"><span>100</span>
					</ul>
				</div>
				<div class="w3-col s5 w3-margin">
					<ul>
						<li>Programme</li>
						<input type="checkbox" name="100" value="100"><span>RGN</span>
					</ul>
				</div>
				<div class="w3-col s5 w3-margin">
					<ul>
						<li>Course</li>
						<input type="checkbox" name="anatomy 1"><span>Anatomy 1</span>
					</ul>
				</div>
				<div class="w3-col s5 w3-margin">
					<ul>
						<li>Time</li>
						<input type="checkbox" name="100"><span>10 min</span>
					</ul>
				</div>
				<div class="w3-bar w3-col s12 w3-center w3-margin">
					<button type="submit" class="w3-button w3-blue">Apply filter</button>
				</div>
			</form>
		</div>
	</div>

	<!-- quizes -->
	<div class="">
		<div class="w3-row w3-margin">
			{% for quiz in quizList %}
			<div class="w3-col l3 m5 s11 w3-card-4 w3-round">
				<a href="{% url 'tquiz:startwork' quiz.name %}">
					<ul class="w3-col s8">
						<li>Name: {{quiz.name}} </li>
						<li>Course: {{quiz.course}} </li>
						<li> Subject: {{quiz.subject}} </li>
						<li> Time : {{quiz.time}}</li>
					</ul>
				
					<div class="w3-col s4">
						{% load static %}
						<img src="{% static 'tquiz/img/myself.jpg' %}" class="w3-image w3-round">
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

</div>
{% endblock %}

Exam/tquiz/templates/tquiz/results.html
{% extends './base.html' %}


{% block content %}
<div style="position: relative; top: 60px;">
	<div class="w3-card-4 w3-margin w3-padding">
		<p>Correct Answer(s): {{ results.correct }}</p>
		<p>Wrong Answer(s): {{ results.wrong }}</p>
		<p>Unaswered Question(s): {{ results.miss }}</p>
		<p class="m-scheme"> Click <span class="w3-button w3-blue w3-round-xxlarge">here </span>to view detailed results and marking scheme </p>
	</div>

	<div id="detailed-res" class="w3-hide w3-margin">
		<ol type="1">
			{% for question, answer in results.marking_scheme.items %}
			<li>{{question}}</li>
			<p>Ans: {{answer}}</p>
			{% endfor %}
		</ol>
	</div>
</div>


{% endblock %}

Exam/tquiz/templates/tquiz/start-work.html
{% extends './base.html' %}

{% block content %}

<!-- Progress bar -->
<div   style="position: relative; top : 80px;">
	<div id="myProgress"><div id="myBar">1%</div>
</div>
<div style="position: relative; top: 70px;">
	<!-- tab controllers -->
	<div class="w3-row">
		<div class="w3-col s6 w3-center w3-padding active not-answered tabNav">Not Answered</div>
		<div class="w3-col s6 w3-center w3-padding answered tabNav w3-blue">Answered</div>
	</div>

	<!-- tab content -->
	<div>
		<div class="tabContent" id="not-answered">
			<div class="w3-row w3-margin">
				<form method="post" action="{% url 'tquiz:results' %}">
					{% csrf_token %}
					<div class="w3-col s11 w3-card-4">
						<ol type="1">
							{% for question, choices in questionList.items %}
							<li>{{question}}</li>
							<ol type="a">
								{% for choice in choices %}
								<li><input type="radio" name="{{question}}" id='{{choice.choice}}' value="{{choice.choice}}">
									<label for="{{choice.choice}}">{{choice.choice}}</label>
								</li>
								{% endfor %}
							</ol>
							{% endfor %}
						</ol>
						<input type="submit" id="auto-submit" hidden="hidden">
					</div>
				</form>
				
			</div>
		</div>

		<div class="w3-hide tabContent" id="answered">
			<h6>Answered questions</h6>
		</div>
	</div>

</div>

{% endblock %}